# Numpy

–ú–∞—Ç–µ—Ä–∏–∞–ª—ã:
* –ú–∞–∫—Ä—É—à–∏–Ω –°.–í. "–õ–µ–∫—Ü–∏—è 1: –ë–∏–±–ª–∏–æ—Ç–µ–∫–∞ Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## –ó–∞–¥–∞—á–∏ –¥–ª—è —Å–æ–≤–º–µ—Å—Ç–Ω–æ–≥–æ —Ä–∞–∑–±–æ—Ä–∞

1. –°–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞—Ç—å –¥–≤—É—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤ `arr` —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ (4, 7), —Å–æ—Å—Ç–æ—è—â–∏–π –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω—ã—Ö —á–∏—Å–µ–ª, —Ä–∞–≤–Ω–æ–º–µ—Ä–Ω–æ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã—Ö –≤ –¥–∏–∞–ø–∞–∑–æ–Ω–µ –æ—Ç 0 –¥–æ 20. –ù–æ—Ä–º–∞–ª–∏–∑–æ–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏—è –º–∞—Å—Å–∏–≤–∞ —Å –ø–æ–º–æ—â—å—é –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è –≤–∏–¥–∞  $ùëéùë•+ùëè$  —Ç–∞–∫, —á—Ç–æ –ø–æ—Å–ª–µ –Ω–æ—Ä–º–∞–ª–∏–∑–∞—Ü–∏–∏ –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–π —ç–ª–µ–º–µ–Ω—Ç –º–∞—Åc–∏–≤–∞ –±—É–¥–µ—Ç —Ä–∞–≤–µ–Ω 1.0, –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–π 0.0

In [4]:
import numpy as np

In [16]:
a = np.random.randint(0, 20, size = (4, 7))
b = np.random.randint(0, 20, size = (4, 7))
print(a)
print(b)

[[ 0  0 19  2 16  8  8]
 [ 4 16 18 16  7 10  9]
 [ 2 11  6  2  6  1  0]
 [ 6 12 15 14 13  3 14]]
[[16  1 12 19 14  5  1]
 [ 1 10  4  7 14  9 17]
 [16 18 11 16  1  5 10]
 [12  1 18 16  0 19  2]]


2. –°–æ–∑–¥–∞—Ç—å –º–∞—Ç—Ä–∏—Ü—É 8 –Ω–∞ 10 –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö —Ü–µ–ª—ã—Ö (–∏—Å–ø–æ–ª—å–∑—É—è –º–æ–¥—É–ª—å `numpy.random`) —á–∏—Å–µ–ª –∏–∑ –¥–∏–∞–ø–æ–∑–æ–Ω–∞ –æ—Ç 0 –¥–æ 10 –∏ –Ω–∞–π—Ç–∏ –≤ –Ω–µ–π —Å—Ç—Ä–æ–∫—É (–µ–µ –∏–Ω–¥–µ–∫—Å –∏ –≤—ã–≤–µ—Å—Ç–∏ —Å–∞–º—É —Å—Ç—Ä–æ–∫—É), –≤ –∫–æ—Ç–æ—Ä–æ–π —Å—É–º–º–∞ –∑–Ω–∞—á–µ–Ω–∏–π –º–∏–Ω–∏–º–∞–ª—å–Ω–∞.

In [18]:
arr = np.random.randint(0, 10, size = (8, 10))
s = []
print(arr)
for string in arr:
    s.append(sum(string))
print(arr[s.index(min(s))])

[[2 0 8 4 2 7 4 8 9 4]
 [8 3 9 7 1 1 4 9 9 7]
 [1 5 0 6 3 4 1 9 4 1]
 [7 5 9 7 6 7 0 1 5 9]
 [2 0 9 7 7 9 5 6 5 1]
 [7 5 5 1 3 3 8 9 7 1]
 [6 1 3 0 6 3 1 4 2 7]
 [1 3 3 6 6 8 7 8 8 2]]
[6 1 3 0 6 3 1 4 2 7]


3. –ù–∞–π—Ç–∏ –µ–≤–∫–ª–∏–¥–æ–≤–æ —Ä–∞—Å—Å—Ç–æ—è–Ω–∏–µ –º–µ–∂–¥—É –¥–≤—É–º—è –æ–¥–Ω–æ–º–µ—Ä–Ω—ã–º–∏ –≤–µ–∫—Ç–æ—Ä–∞–º–∏ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–π —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

In [3]:
import numpy as np
single_point = [3, 4]
points = np.arange(20).reshape((10,2))

dist = (points - single_point)**2
dist = np.sum(dist, axis=1)
dist = np.sqrt(dist)
dist

array([ 4.24264069,  1.41421356,  1.41421356,  4.24264069,  7.07106781,
        9.89949494, 12.72792206, 15.55634919, 18.38477631, 21.21320344])

4. –†–µ—à–∏—Ç—å –º–∞—Ç—Ä–∏—á–Ω–æ–µ —É—Ä–∞–≤–Ω–µ–Ω–∏–µ `A*X*B=-C` - –Ω–∞–π—Ç–∏ –º–∞—Ç—Ä–∏—Ü—É `X`. –ì–¥–µ `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## –õ–∞–±–æ—Ä–∞—Ç–æ—Ä–Ω–∞—è —Ä–∞–±–æ—Ç–∞ ‚Ññ1

–ó–∞–º–µ—á–∞–Ω–∏–µ: –ø—Ä–∏ —Ä–µ—à–µ–Ω–∏–∏ –¥–∞–Ω–Ω—ã—Ö –∑–∞–¥–∞—á –Ω–µ –ø–æ–¥—Ä–∞–∑—É–º–µ–≤–∞–µ—Ç—Å—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ü–∏–∫–ª–æ–≤ –∏–ª–∏ –≥–µ–Ω–µ—Ä–∞—Ç–æ—Ä–æ–≤ Python, –µ—Å–ª–∏ –≤ –∑–∞–¥–∞–Ω–∏–∏ –Ω–µ —Å–∫–∞–∑–∞–Ω–æ –æ–±—Ä–∞—Ç–Ω–æ–≥–æ. –†–µ—à–µ–Ω–∏–µ –¥–æ–ª–∂–Ω–æ –æ–ø–∏—Ä–∞—Ç—å—Å—è –Ω–∞ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª–∞ –±–∏–±–ª–∏–æ—Ç–µ–∫–∏ `numpy`.

1. –§–∞–π–ª `minutes_n_ingredients.csv` —Å–æ–¥–µ—Ä–∂–∏—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ–± –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–µ —Ä–µ—Ü–µ–ø—Ç–∞, –≤—Ä–µ–º–µ–Ω–∏ –µ–≥–æ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –≤ –º–∏–Ω—É—Ç–∞—Ö –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤. –°—á–∏—Ç–∞–π—Ç–µ –¥–∞–Ω–Ω—ã–µ –∏–∑ —ç—Ç–æ–≥–æ —Ñ–∞–π–ª–∞ –≤ –≤–∏–¥–µ –º–∞—Å—Å–∏–≤–∞ `numpy` —Ç–∏–ø–∞ `int32`, –∏—Å–ø–æ–ª—å–∑—É—è `np.loadtxt`. –í—ã–≤–µ–¥–∏—Ç–µ –Ω–∞ —ç–∫—Ä–∞–Ω –ø–µ—Ä–≤—ã–µ 5 —Å—Ç—Ä–æ–∫ –º–∞—Å—Å–∏–≤–∞.

In [3]:
import numpy as np
table = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
print(table[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ, –º–∏–Ω–∏–º—É–º, –º–∞–∫—Å–∏–º—É–º –∏ –º–µ–¥–∏–∞–Ω—É –ø–æ –∫–∞–∂–¥–æ–º—É –∏–∑ —Å—Ç–æ–ª–±—Ü–æ–≤, –∫—Ä–æ–º–µ –ø–µ—Ä–≤–æ–≥–æ.

In [4]:
data = table[:,1:]
means = np.mean(data, axis=0)
mins = np.min(data, axis=0)
maxs = np.max(data, axis=0)
medians = np.median(data, axis=0)

print("Means: ", means)
print("Mins: ", mins)
print("Max: ", maxs)
print("Medians: ", medians)

Means:  [2.16010017e+04 9.05528000e+00]
Mins:  [0 1]
Max:  [2147483647         39]
Medians:  [40.  9.]


3. –û–≥—Ä–∞–Ω–∏—á—å—Ç–µ —Å–≤–µ—Ä—Ö—É –∑–Ω–∞—á–µ–Ω–∏—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è —Ä–µ—Ü–µ–ø—Ç–∞ –∑–Ω–∞—á–µ–Ω–∏–µ–º –∫–≤–∞–Ω—Ç–∏–ª—è $q_{0.75}$. 

In [5]:
table[:,1] = np.clip(table[:,1], 0, np.quantile(table[:,1], 0.75))
table

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, –¥–ª—è —Å–∫–æ–ª—å–∫–∏—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ —É–∫–∞–∑–∞–Ω–∞ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å, —Ä–∞–≤–Ω–∞—è –Ω—É–ª—é. –ó–∞–º–µ–Ω–∏—Ç–µ –¥–ª—è —Ç–∞–∫–∏—Ö —Å—Ç—Ä–æ–∫ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ –¥–∞–Ω–Ω–æ–º —Å—Ç–æ–ª–±—Ü–µ –Ω–∞ 1.

In [6]:
print(len(table[table[:,1] == 0]))
table[table[:,1] == 0] = 1

479


5. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ.

In [7]:
len(np.unique(table[:,0]))

99522

6. –°–∫–æ–ª—å–∫–æ –∏ –∫–∞–∫–∏—Ö —Ä–∞–∑–ª–∏—á–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –∫–æ–ª-–≤–∞ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Å—É—Ç–≤—É–µ—Ç –≤ —Ä–µ—Ü–µ–ø—Ç–∞—Ö –∏–∑ –¥–∞—Ç–∞—Å–µ—Ç–∞?

In [8]:
uni2=set(table[:,2])
print(len(uni2))
print(*np.unique(table[:,2]))

37
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 37 39


7. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –º–∞—Å—Å–∏–≤–∞, —Å–æ–¥–µ—Ä–∂–∞—â—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é —Ç–æ–ª—å–∫–æ –æ —Ä–µ—Ü–µ–ø—Ç–∞—Ö, —Å–æ—Å—Ç–æ—è—â–∏—Ö –Ω–µ –±–æ–ª–µ–µ —á–µ–º –∏–∑ 5 –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤.

In [9]:
under = np.copy(table)
mask = (under[:,2] <= 5)
under[mask, :]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. –î–ª—è –∫–∞–∂–¥–æ–≥–æ —Ä–µ—Ü–µ–ø—Ç–∞ –ø–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ –≤ —Å—Ä–µ–¥–Ω–µ–º –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Ö–æ–¥–∏—Ç—Å—è –Ω–∞ –æ–¥–Ω—É –º–∏–Ω—É—Ç—É —Ä–µ—Ü–µ–ø—Ç–∞. –ù–∞–π–¥–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —ç—Ç–æ–π –≤–µ–ª–∏—á–∏–Ω—ã –¥–ª—è –≤—Å–µ–≥–æ –¥–∞—Ç–∞—Å–µ—Ç–∞

In [10]:
value = table[:, 2] / table[:, 1]
print(value.max(axis=0))

23.0


9. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –¥–ª—è —Ç–æ–ø-100 —Ä–µ—Ü–µ–ø—Ç–æ–≤ —Å –Ω–∞–∏–±–æ–ª—å—à–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é

In [11]:
sort = table[table[:,1].argsort()[::1]][-100:]
np.mean(sort[:, 2])

9.96

10. –í—ã–±–µ—Ä–∏—Ç–µ —Å–ª—É—á–∞–π–Ω—ã–º –æ–±—Ä–∞–∑–æ–º –∏ –≤—ã–≤–µ–¥–∏—Ç–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ 10 —Ä–∞–∑–ª–∏—á–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–∞—Ö

In [14]:
lst = np.random.randint(1, 100000, size = (1,10))
print(table[lst])

[[[417804     10      6]
  [352468      9      7]
  [ 26174     30     11]
  [357017     30      8]
  [237868     45     13]
  [258515     26      7]
  [367949     65     13]
  [247900     65     19]
  [ 50993     45     10]
  [275754     50     12]]]


11. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç —Ä–µ—Ü–µ–ø—Ç–æ–≤, –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä—ã—Ö –º–µ–Ω—å—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ.

In [17]:
len(table[(table[:,2] <= np.mean(table[:,2]))]) / len(table) * 100

58.989000000000004

12. –ù–∞–∑–æ–≤–µ–º "–ø—Ä–æ—Å—Ç—ã–º" —Ç–∞–∫–æ–π —Ä–µ—Ü–µ–ø—Ç, –¥–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –∫–æ—Ç–æ—Ä–æ–≥–æ –Ω–µ –±–æ–ª—å—à–µ 20 –º–∏–Ω—É—Ç –∏ –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä–æ–º –Ω–µ –±–æ–ª—å—à–µ 5. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –¥–∞—Ç–∞—Å–µ—Ç–∞ —Å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–º —Å—Ç–æ–ª–±—Ü–æ–º, –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ –∫–æ—Ç–æ—Ä–æ–≥–æ —è–≤–ª—è—é—Ç—Å—è 1, –µ—Å–ª–∏ —Ä–µ—Ü–µ–ø—Ç –ø—Ä–æ—Å—Ç–æ–π, –∏ 0 –≤ –ø—Ä–æ—Ç–∏–≤–Ω–æ–º —Å–ª—É—á–∞–µ.

In [16]:
data = table.copy()
prost = [1 if (row[1] <= 20) & (row[2] <= 5) else 0 for row in data]
new_data = np.insert(data, 3, prost, axis=1)
new_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç "–ø—Ä–æ—Å—Ç—ã—Ö" —Ä–µ—Ü–µ–ø—Ç–æ–≤ –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ

In [18]:
len(new_data[(new_data[:,3] == 1)]) / len(table) * 100 

9.943

14. –†–∞–∑–¥–µ–ª–∏–º —Ä–µ—Ü–µ–ø—Ç—ã –Ω–∞ –≥—Ä—É–ø–ø—ã –ø–æ —Å–ª–µ–¥—É—é—â–µ–º—É –ø—Ä–∞–≤–∏–ª—É. –ù–∞–∑–æ–≤–µ–º —Ä–µ—Ü–µ–ø—Ç—ã –∫–æ—Ä–æ—Ç–∫–∏–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –º–µ–Ω–µ–µ 10 –º–∏–Ω—É—Ç; —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –±–æ–ª–µ–µ 10, –Ω–æ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç; –∏ –¥–ª–∏–Ω–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –Ω–µ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç. –°–æ–∑–¥–∞–π—Ç–µ —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤, –≥–¥–µ –Ω—É–ª–µ–≤–∞—è –æ—Å—å –æ—Ç–≤–µ—á–∞–µ—Ç –∑–∞ –Ω–æ–º–µ—Ä –≥—Ä—É–ø–ø—ã (–∫–æ—Ä–æ—Ç–∫–∏–π, —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–π –∏–ª–∏ –¥–ª–∏–Ω–Ω—ã–π —Ä–µ—Ü–µ–ø—Ç), –ø–µ—Ä–≤–∞—è –æ—Å—å - –∑–∞ —Å–∞–º —Ä–µ—Ü–µ–ø—Ç –∏ –≤—Ç–æ—Ä–∞—è –æ—Å—å - –∑–∞ —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏ —Ä–µ—Ü–µ–ø—Ç–∞. –í—ã–±–µ—Ä–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–µ—Ü–µ–ø—Ç–æ–≤ –∏–∑ –∫–∞–∂–¥–æ–π –≥—Ä—É–ø–ø—ã —Ç–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, —á—Ç–æ–±—ã –±—ã–ª–æ –≤–æ–∑–º–æ–∂–Ω–æ —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤. –í—ã–≤–µ–¥–∏—Ç–µ —Ñ–æ—Ä–º—É –ø–æ–ª—É—á–µ–Ω–Ω–æ–≥–æ –º–∞—Å—Å–∏–≤–∞.